Repository exposy/exposy-cli, pull requests merged in 2022-10, with the labels that each got.

#2 Add basic documentation with design diagrams
  README.md
Labels: hacktoberfest

#4 fix: detect & report invalid target port
  src/commands/start.js
Labels: hacktoberfest

#5 Add workflow to bump & npm release workflow
  .github/workflows/release.yml
  package-lock.json
  package.json
Labels: hacktoberfest-accepted, hacktoberfest

#7 Added contrinution steps in readme
  README.md
Labels: hacktoberfest-accepted
